name: apbelem
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.3"

dependencies:
  cupertino_icons: ^1.0.2
  edge_alert: ^0.0.1
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_open_whatsapp: ^0.1.2
  flutter_speed_dial: ^4.3.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.6.0
  get: ^4.1.4
  get_storage: null
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  image_cropper: ^1.4.0
  image_picker: ^0.7.2
  intl: ^0.17.0
  mask_text_input_formatter: ^1.2.1
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.2
  table_calendar: ^3.0.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/cliente.png
